# Generated by Django 5.2.8 on 2025-11-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='viewstartup',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='viewstartup',
            name='technologies',
            field=models.CharField(max_length=400),
        ),
    ]
