# Generated by Django 5.2.8 on 2025-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_notifications_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='Complaints',
            new_name='complaints',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Reply',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='doubt',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='doubt',
            old_name='Doubt',
            new_name='doubt',
        ),
        migrations.RenameField(
            model_name='doubt',
            old_name='Reply',
            new_name='reply',
        ),
    ]
