# Generated by Django 5.2.8 on 2025-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_complaints_complaints_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaints',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='reply',
            field=models.CharField(max_length=1000),
        ),
    ]
