# Generated by Django 5.2.8 on 2025-11-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_complaints_complaints_alter_complaints_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentrequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('request_reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
        ),
    ]
