# Generated by Django 5.2.8 on 2025-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='photo',
            field=models.ImageField(upload_to='verexpeuser'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='proof',
            field=models.ImageField(upload_to='expeproof'),
        ),
    ]
