# Generated by Django 5.2.8 on 2025-11-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_experts_photo_alter_experts_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experts',
            name='pin',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='pin',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to='studuser'),
        ),
        migrations.DeleteModel(
            name='Studentrequests',
        ),
    ]
