# Generated by Django 5.2.8 on 2025-12-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_experts_phone_experts_pin_students_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('request_reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
        ),
    ]
