# Generated by Django 5.2.8 on 2025-12-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.viewstartup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academics', models.CharField(max_length=1000)),
                ('tech_skills', models.CharField(max_length=1000)),
                ('interests', models.CharField(max_length=1000)),
                ('pref_industry', models.CharField(max_length=1000)),
                ('investment_cap', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
            ],
        ),
    ]
