# Generated by Django 5.2.8 on 2026-01-28 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bookmark_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_requests'),
        ),
    ]
