
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path("public/", views.public),
    path("login/", views.logins),
    path("login_post/", views.login_post),
    path("signup/", views.signup),
    path("admin_homepage/", views.admin_home),
    path("add_idea/", views.add_idea),
    path("add_idea_post/", views.add_idea_post),
    path("add_idea_e/", views.add_idea_e),
    path("add_idea_e_post/", views.add_idea_e_post),
    path("edit_idea/<id>", views.edit_idea),
    path("edit_idea_post/", views.edit_idea_post),
    path("delete_idea/<id>", views.delete_idea),
    path("add_notif/", views.add_notif),
    path("add_notif_post/", views.add_notif_post),
    path("delete_notif/<id>", views.delete_notif),
    path("send_reply/<id>", views.send_reply),
    path("send_reply_post/", views.send_reply_post),
    path("change_pass_a/", views.change_pass_a),
    path("change_pass_a_post/", views.change_pass_a_post),
    path("view_students/", views.view_students),
    path("view_experts/", views.view_experts),
    path("approve_experts/<id>", views.approve_experts),
    path("reject_experts/<id>", views.reject_experts),
    path("view_idea/", views.view_idea),
    path("view_notif/", views.view_notif),
    path("view_feedback_a/", views.view_feedback_a),
    path("view_review_rating/", views.view_review_rating),
    path("view_complaints_reply/", views.view_complaints_reply),
    path("view_requests/", views.view_requests),
    path("register_expert/", views.register_expert),
    path("register_expert_post/", views.register_expert_post),
    path("expert_homepage/", views.expert_homepage),
    path("view_profile_e/", views.view_profile_e),
    path("view_studentdoubts/", views.view_studentdoubts),
    path("send_reply_e/<id>",views.send_reply_e),
    path("send_reply_e_post/",views.send_reply_e_post),
    path("send_reply_e2/<id>",views.send_reply_e2),
    path("send_reply_e2_post/",views.send_reply_e2_post),
    path("view_feedback_e/", views.view_feedback_e),
    path("view_review_rating_e/", views.view_review_rating_e),
    path("change_pass_e/", views.change_pass_e),
    path("change_pass_e_post/", views.change_pass_e_post),
    path("edit_profile/",views.edit_profile),
    path("edit_profile_post/", views.edit_profile_post),
    path("logout/", views.logout),
    path('register_page/',views.register_page),
    path("Login_page/",views.Login_page),
    path("user_home/",views.user_home),
    path("manage_profile/",views.manage_profile),
    path("Editprof/",views.Editprof),
    path("Editprof_post/",views.Editprof_post),
    path("Changepass/",views.Changepass),
    path("Expert_idea/",views.Expert_idea),
    path("Expert_idea_post/",views.Expert_idea_post),
    path("Complaints_user/", views.Complaints_user),
    path("Complaints_user_post/", views.Complaints_user_post),
    path("Doubts_user/",views.Doubts_user),
    path("Doubts_user_post/",views.Doubts_user_post),
    path("Feedback_user/",views.Feedback_user),
    path("Feedback_user_post/",views.Feedback_user_post),
    path("Rating_review/",views.Rating_review),
    path("chatbot_response/",views.chatbot_response),
    path("Rating_review_post/",views.Rating_review_post),
    path("save_student_details/",views.save_student_details),
    path("add_bookmark/", views.add_bookmark),
    path("get_bookmarks/", views.get_bookmarks, name='get_bookmarks'),
    path("remove_bookmark/", views.remove_bookmark, name='remove_bookmark'),
    path('get_notifications/', views.get_notifications, name='get_notifications')
]
